### ISSUE TITLE
Fortigate VM 7.2.1 不能获取root权限

### ISSUE THREAD

**Issue by BeforeGodKnows** [rrrrrrri/fgt-auto-repack#1]
你好，我在按照你的博客和提供的代码repack 7.2.1版本的rootfs.gz并尝试获取root权限的shell，我已经成功获得了shell。但是，我在尝试使用“killall sshd”和“busybox telnetd -l /bin/sh -b 0.0.0.0 -p 22”命令时，系统报错分别为
![image](https://github.com/rrrrrrri/fgt-auto-repack/assets/91412440/71b7c3c6-aa78-4fd4-bdf4-73cda6851361)
![image](https://github.com/rrrrrrri/fgt-auto-repack/assets/91412440/24fc049e-166d-4ea8-8468-3a0cbc990f54)
我用的是你提供的busybox，请问这种情况该如何解决？谢谢你的帮助

**Comment by rrrrrrri** [comment]
> 你好，我在按照你的博客和提供的代码repack 7.2.1版本的rootfs.gz并尝试获取root权限的shell，我已经成功获得了shell。但是，我在尝试使用“killall sshd”和“busybox telnetd -l /bin/sh -b 0.0.0.0 -p 22”命令时，系统报错分别为 ![image](https://user-images.githubusercontent.com/91412440/272522213-71b7c3c6-aa78-4fd4-bdf4-73cda6851361.png) ![image](https://user-images.githubusercontent.com/91412440/272522531-24fc049e-166d-4ea8-8468-3a0cbc990f54.png) 我用的是你提供的busybox，请问这种情况该如何解决？谢谢你的帮助

试试 在 meterpreter 中先执行 shell 命令，再执行以上命令。

**Comment by BeforeGodKnows** [comment]
> > 你好，我在按照你的博客和提供的代码repack 7.2.1版本的rootfs.gz并尝试获取root权限的shell，我已经成功获得了shell。但是，我在尝试使用“killall sshd”和“busybox telnetd -l /bin/sh -b 0.0.0.0 -p 22”命令时，系统报错分别为 ![image](https://user-images.githubusercontent.com/91412440/272522213-71b7c3c6-aa78-4fd4-bdf4-73cda6851361.png) ![image](https://user-images.githubusercontent.com/91412440/272522531-24fc049e-166d-4ea8-8468-3a0cbc990f54.png) 我用的是你提供的busybox，请问这种情况该如何解决？谢谢你的帮助
> 
> 试试 在 meterpreter 中先执行 shell 命令，再执行以上命令。

感谢你的帮助，已经成功解决了

**Comment by BeforeGodKnows** [comment]
还有个问题想要麻烦你。你在后序调试时，是不是通过busybox上传了一个静态编译的gdb进入了系统？如果是的话，能请问这个静态编译的gdb版本是多少吗？能麻烦你提供一下你编译好的gdb吗？谢谢你

**Comment by rrrrrrri** [comment]
> 还有个问题想要麻烦你。你在后序调试时，是不是通过busybox上传了一个静态编译的gdb进入了系统？如果是的话，能请问这个静态编译的gdb版本是多少吗？能麻烦你提供一下你编译好的gdb吗？谢谢你

gdbserver 7.12 版本，你可以自己下载源码编译。

**Comment by BeforeGodKnows** [comment]
> > 还有个问题想要麻烦你。你在后序调试时，是不是通过busybox上传了一个静态编译的gdb进入了系统？如果是的话，能请问这个静态编译的gdb版本是多少吗？能麻烦你提供一下你编译好的gdb吗？谢谢你
> 
> gdbserver 7.12 版本，你可以自己下载源码编译。

好的，非常感谢你的帮助
